spring:
  application:
    name: notification-service

  # 데이터베이스 설정
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/liveklass_noti}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100 # N+1 문제 방지 최적화

  # Redis 설정
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
