spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:h2:file:./db/notification;MODE=MySQL;NON_KEYWORDS=VALUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100 # N+1 문제 방지 최적화

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  override-with-generic-response: false  # ApiResponse<T> 제네릭 타입 resolve 오류 방지
